---
title: "Nonprofit CEO Compensation Appraisal Tool"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(ggplot2)
library(dplyr)
library(kableExtra)
library(compensator)
library(DT)

```



Compensation Tool 
=======================================================================


Row
-----------------------------------------------------------------------

### Welcome to the Nonprofit CEO Compensation Appraisal Tool! 


Please enter the following information then click submit. 


```{r}
# Input State 
selectInput(inputId = "input.org.state",
            label = "State",
            choices = state.abb52)

# Input Location
selectInput(inputId = "input.org.location",
            label = "Location Type",
            choices = c("Metropolitan", "Rural"))

# Input Total Expenses
numericInput(inputId = "input.org.expense", 
             label = "Total Annual Expenses", 
             value = 100000, 
             min = 1e5,
             max = 1e10)

# NTEE Input
textInput(inputId = "input.org.ntee",
          label = "NTEE Code",
          value = "A24")

# Generate Report 

actionButton(inputId = "generate",
             label = "Generate Appraisal")

apprasial <- eventReactive(input$generate, {
  
  loc <- dplyr::case_when(input$input.org.location == "Metropolitan" ~ "metro",
                          input$input.org.location == "Rural" ~ "rural")
  
  org <- compensator::get_org_values(state = input$input.org.state,
                                     location.type = loc,
                                     total.expense = input$input.org.expense,
                                      ntee = input$input.org.ntee)
  

  search.criteria <-
  list(broad.category = org$broad.category,
       major.group = base::LETTERS,
       tens = 0:9,
       type.org = org$type.org,
       univ = org$univ,
       hosp = org$hosp,
       location.type = org$location.type,
       state = state.abb52,
       total.expense = c(0.1*org$total.expense, 10*org$total.expense) )
  
  samp <- select_sample(org = org, search.criteria = search.criteria)
  predict_salary(samp)
  
  })

renderPrint({
  # print(apprasial()[[2]])
  app <- apprasial()
  print(paste0("Your suggested salary is ", dollarize(round(app[[2]][1], 0)), " - ", dollarize(round(app[[2]][2],0)), "."))
  })




```




Detailed Appraisal
=======================================================================

### Recent Downlads

```{r}
mtcars %>%
  kable()
```


About
=======================================================================


Here is we will put the about information 


Gender Pay Gaps
=======================================================================

Here is where we will put the gender pay gap graphs




